author: eccentric_nz
description: A simple shop plugin for TARDIS items
main: me.eccentric_nz.tardisshop.TARDISShop
name: TARDISShop
load: POSTWORLD
version: 1.0.2
api-version: 1.18
website: http://tardisjenkins.duckdns.org:8080/job/TARDISShop/
url: http://tardisjenkins.duckdns.org:8080/job/TARDISShop/
permissions:
  tardisshop.use:
    description: Allow players to buy items from a TARDIS Shop.
    default: op
  tardisshop.admin:
    description: Allow players to set up a TARDIS Shop.
    default: op
commands:
  tardisshop:
    aliases: [tshop]
    description: Add and remove TARDISShop items.
    usage: /<command> [add|remove|update] [item_name]
    permission: tardisshop.admin
    permission-message: You don't have the permission <permission> to use this command
depend: [TARDIS,Vault]
soft-depend: [TARDISWeepingAngels]
